### ISSUE TITLE
Error parsing

### ISSUE THREAD

**Issue by nullproduction** [simhanature/SHXMLParser#1]
Hi, I found an error.
When parsing itunes rss  - http://brand.podfm.ru/rss/rss.xml 
tag itunes:image improperly handled.

**In:**

```
<itunes:image href="http://file2.podfm.ru/14/141/1416/14165/images/pod_876_or.jpg">
</itunes:image>
```

**Out:**

```
itunes:image" = "\n";
```

**Comment by simhanature** [comment]
Thanks for opening the issue.
For proper object conversion, it is good to have only direct text or just attributes in the leaf nodes. It is because of this case, object conversion missed attribute contents.
I have fixed this issue now. 
Only in the above leaf node case, direct contents in the leaf node will be accessed by the key 'leafContent' and attributes can be accessed properly as before.

**Comment by nullproduction** [comment]
Thanks for fix :)
